Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provision "file", source: "index.html", destination: "/vagrant/index.html"
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y nginx
  SHELL
  config.vm.provision "file", source: "nginx.conf", destination: "/tmp/nginx.conf"
  config.vm.provision "shell", inline: <<-SHELL
    cp /tmp/nginx.conf /etc/nginx/sites-available/default
    ginx -t
    systemctl restart nginx
  SHELL
end
